### ISSUE TITLE
[Suggestion] Make option: Allow Longer Break Times

### ISSUE THREAD

**Issue by frqnny** [grondag/trees-dont-float#11]
It's unrealistic sometimes having trees fall very easily. You should have an option to make that time slower since it is a little unbalanced.

**Comment by grondag** [comment]
Have you already changed the `maxBreaksPerTick` config option to 1?

**Comment by paulPablito** [comment]
Changing maxBreaksPerTick to 1 simply makes it so that you have to watch your tree being automatically felled for a bit longer. I propose, there be an option akin to TreeCapitator, where you take a combined amount of time for every block in breaking one block, and then everything falls.

**Comment by grondag** [comment]
Hmm, would have tone  limited to the configuration where an axe is required, but that is doable.  Making the duration last based on tree size will be a little tricker but also doable.  No idea when, but will probably add this.

**Comment by frqnny** [comment]
heyo, grondag! just wanted an update on this if it has been implemented and if not, i just want to revive the idea.

**Comment by grondag** [comment]
Not implemented.  Looked at it today and it will take some doing to make it perform well.   Will be too slow to check the tree each hit,  which means the result has to be cached, and then that cache has to be invalidated when the world changes, handle multi-player correctly, etc.  

Not saying it won't happen, but I don't have time for it right now. Other mods need the attention more.

**Comment by franiscoder** [comment]
Couldn't you just change the hardness of blocks?

**Comment by grondag** [comment]
Slower break speeds added in V2
