### ISSUE TITLE
Properties not working?

### ISSUE THREAD

**Issue by pjlasl** [grondag/trees-dont-float#17]
I used to use a datapack that had the option to drop items directly into the player's inventory. Hoping you had a similar property, I found one called "directdeposit", but it doesn't seem to work. When I broke an oak tree the items just dropped to the ground.

I also noticed, maybe incorrectly, that the stacked property isn't stacking the items, I see multiple piles of saplings or logs when a tree is chopped down.

**Comment by pjlasl** [comment]
This was my fault. I realized after that I had not restarted my server :/.

**Comment by grondag** [comment]
Cool.  Thanks for letting me know.
