### ISSUE TITLE
[Suggestion] Leaf exclusion

### ISSUE THREAD

**Issue by MechanosG** [grondag/trees-dont-float#19]
Heya.  I nabbed this mod for the "falling over" functionality instead of vein miner functionality, which is neat.  It seems to work well (although it does occasionally leave behind some thicc branches in the air).  I would like a config option to turn off the exploding of leaves though.  I'm wanting to test leaving behind the leaves and having them decay naturally (possibly sped up with another mod), rather than "poof, gone", but I don't think I see an option for that.  In theory that should reduce some of the tree chopping lag and might be aesthetically pleasing (I really like realism/survivalism mods).

**Comment by grondag** [comment]
Don't know when I'll get to it but this is very doable.

**Comment by grondag** [comment]
Added in V2.0. https://github.com/grondag/trees-dont-float/commit/01d7a5f57c79dd3c2af27c1f2eae4b606e7a4598
