### ISSUE TITLE
[1.16.3] Trees Dont Float crashes structure processor json 

### ISSUE THREAD

**Issue by TelepathicGrunt** [grondag/trees-dont-float#21]
Hello! Someone found that my nether temples in Repurposed Structures was crashing and after some digging, I found it crashes only when Trees Dont Float is on. 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/36

This is the same issue as I have found with another mod who was also injecting new properties into blocks:
https://github.com/Eilux/BetterSlabs/issues/2

Basically what is happening is for worldgen datapacks (and mods if they use the same json), the structure processor json defines the block's property. If the user puts too many properties or omits one, the processor breaks when Minecraft parses it and ends up causing the structure pool to explode. Thus, makes the structure crash upon generation as the game sees the pool as empty which is an invalid state (causes a random.nextInt(poolElementSize) to crash due to size being 0). My Warped and Crimson Temples uses the Hyphae blocks which seems to have been affected by Trees Dont Float.

I was talking with others about this problem and there seems to be two fixes. Fix 1 being to use a mixin to change how the codec works for processors. The second fix is to use Virtuoel's api called Statement that allows adding properties safely to blocks.
https://discord.com/channels/507304429255393322/566276937035546624/760557211469611018

You can talk to Virtuoel if you want to use his API or need help making Trees Dont Float's property manipulation safe. 

I hope this helps as this cause be an issue for anyone trying worldgen datapacks with this mod on.

**Comment by grondag** [comment]
Thank you for the detailed report and explanation - very helpful. Undecided yet on how I want to fix.

**Comment by RawrMaoster** [comment]
Any update on a fix between these two mods? I cant remove TDNF since it changes all modded blocks to something else for whatever reason and id like to use both <3

**Comment by grondag** [comment]
Fixed in V2.0.  Release imminent.
