### ISSUE TITLE
[Suggestion] Allow multiple tree cut jobs at once

### ISSUE THREAD

**Issue by MechanosG** [grondag/trees-dont-float#22]
Hello again.  Similar to the discussion [Here](https://github.com/grondag/trees-dont-float/issues/11) I tested setting the max breaks per tick to 1, so that trees cut down more slowly.  This actually worked out pretty good.  However, I noticed I can only cut wood 1 block at a time if a cut job is already active.  For example, say I cut down a tree with 7 logs and a lot of leaves.  The tree starts breaking then I try to cut another tree down, or try to cut the logs that fell with the "Keep Logs Intact" setting enabled, while I wait.  This second cut seems to not activate the mod, so only 1 wood block is cut.  Once the leaves are done exploding on the original tree however, I can now start a new tree cut job and have everything works as expected.

So my suggestion, is to allow having more than one tree cut job at once.  That way we can cut the fallen logs or start cutting on another tree, while the first is still working.

**Comment by grondag** [comment]
Feature is added in version 2.0
