### ISSUE TITLE
Compatibility issue with Tech Reborn chainsaw

### ISSUE THREAD

**Issue by Zarepheth** [grondag/trees-dont-float#28]
The first time I cut a tree with a Tech Reborn chainsaw, the whole tree collapsed to the ground and the leaves broke as expected (just like my settings for using any other tools). On subsequent cuts, the chainsaw only broken one log at a time, and the leaves failed to break or decay at the faster speed I would expect from the mod pack and additional mods I'm using.

**Comment by grondag** [comment]
Unable to reproduce with TDNF V3 and TR V5.0.11-beta
