### ISSUE TITLE
Fallen logs not rotating sometimes

### ISSUE THREAD

**Issue by bravely-beep** [grondag/trees-dont-float#30]
On Fabric 1.18, when using the "keep logs intact" functionality, logs sometimes do not switch to their sideways orientation when they fall. This seems to happen with trees that consist of a single vertical trunk with no branches

**Comment by bravely-beep** [comment]
More specifically, this seems to happen when the tree has an equal balance of weight on all sides. I'm assuming this triggers the tree to choose a random direction to fall in, but the log direction is not adjusted accordingly

**Comment by grondag** [comment]
Thanks for the report.   You are correct: axis is not getting set when the tree has a stable center of gravity,
