### ISSUE TITLE
Acacia Trees Don't Grow

### ISSUE THREAD

**Issue by dranorter** [grondag/trees-dont-float#4]
With TDNF, acacia trees usually shatter upon growing from saplings, since they have unsupported blocks (or at least, we could say blocks whose support is only diagonal). Unexpectedly, it doesn't seem to matter whether "requireLogBreak" is true or false. I like "requireLogBreak" to be false, but I don't want tree growth from saplings to be affected.

**Comment by grondag** [comment]
Duplicate of #3.  Will be fixed.
