### ISSUE TITLE
Server bug

### ISSUE THREAD

**Issue by pbsillva** [grondag/trees-dont-float#5]
This mod is working smooth in single player mode.
But when i try to use it in my server i got a few bugs in the map, and the mod stops working.

https://imgur.com/NyGHvkf

I also tried previous versions and still get the same issue.
Atm i'm using tdnf-1.3.0+build.26.jar

**Comment by grondag** [comment]
Hmm, not much to go on.  A few questions:

- Can you be certain the server and clients are all using the same version?
- Dedicated or LAN server?
- Does the problem happen immediately or after a time?
- Does the problem affect every player or only some of them?

Any answers you can offer will help.  Thanks.

**Comment by pbsillva** [comment]
**Can you be certain the server and clients are all using the same version?**

[Sure](https://imgur.com/a/q5ihG4k)

**Dedicated or LAN server?**

LAN, via hamachi.

**Does the problem happen immediately or after a time?**

Immediately after joining the world in the server

**Does the problem affect every player or only some of them?**

Yes, every player.

**Comment by rtester47** [comment]
I get he same results. it works smoothly in single player, but when i connect to any 1.14.4 server all the blocks are scrambled, even my 1.14.4 local host server does the same. I tried adding the latest version downloaded today from your mod site to my client mod folder, and adding it to the server mod folder and removing it from my client folder just in case of conflict. For some unknown reason it scrambles the blocks.

with mod installed.   https://ibb.co/SBvYwN4
with mod removed.  https://ibb.co/G2KnpJC

I have the latest fabric installed, fabric API installed,

**Comment by grondag** [comment]
Alright, thank you for the confirmation.  No idea what is borking it up but will try to replicate.

**Comment by grondag** [comment]
I'm having no luck reproducing this so far.  Will keep looking for clues.

**Comment by grondag** [comment]
@pbsillva @rtester47 It would help me tremendously if either if you could attach:

1) Client log file
2) Server log file
3) Zip of server installation - including server jar and all mods.  That would let me run the exact same server setup and hopefully reproduce.

Thanks much.

**Comment by rtester47** [comment]
I am raring up the server folder i have. but for some reason it started to work right. but for just about any other 1.14.4 multiplayer server I log into I have to remove your mod to get it to display the blocks correctly.

SERVER: hub.bmc.gg  
My SERVER: http://www.mediafire.com/file/gtrp4q9k19fmdas/server.rar/file

as for the client log I have so many in there I would not know which one to give you.

**Comment by grondag** [comment]
Thank you. So it's working now with that rar?

Note that if other servers don't have TDNF installed you will definitely have this problem and it isn't something I can fix.  It happens because of the way clients and servers communicate blocks back and forth.  

TDNF adds a new property to log blocks, and if the server doesn't also have this, they will end up assigning different numbers to block states, which causes this problem. At best, I could detect when it happens and log a warning, but there's no way to disable it per-server because Minecraft expects all the block states to be setup once at startup.

**Comment by KingXigo** [comment]
I have the same problem, it not only happens to private LAN servers but also in public servers in general such as Hypixel, Mineplex, etc.

**Comment by grondag** [comment]
Do those servers have this mod installed?  It does need to be installed on the server to work correctly.

**Comment by Cynosphere** [comment]
Can replicate dedicated server with the mod only installed serverside.

**Comment by grondag** [comment]
Not sure I understand. This mod always needs to be installed on both the server and all clients. There are no textures on the server so I assume you’re seeing the mixup on clients, and that is normal if the mod isn’t installed there. 

Fabric doesn’t have a network handshake yet to check the installed mods match on both client and server so it is easy to have this problem and not realize that both are required.

**Comment by grondag** [comment]
Note that a server-side model would probably be possible except for protecting player-placed logs. Those require new block states and that means the client has to know. That’s been an important feature which is why I’ve not tried a server-only version.

**Comment by Cynosphere** [comment]
> Those require new block states and that means the client has to know.

Which is where this bug is occurring.

A lot of it is just all of us missing the fact that it has to be installed on both client and server.

**Comment by grondag** [comment]
V2.0 is server-side only.
