### ISSUE TITLE
Client Bug

### ISSUE THREAD

**Issue by rmail2006** [grondag/trees-dont-float#6]
Hi Devs,

So I'm using Minecraft version 1.14.2, playing singleplayer.

I chopped a tree down and teh game crahed with teh following error report

----------------

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 15/07/19 19:14
Description: Ticking entity

java.lang.NoSuchFieldError: field_19393
	at grondag.tdnf.FallingLogEntity.method_5773(FallingLogEntity.java:189)
	at net.minecraft.class_3218.method_18762(class_3218.java:580)
	at net.minecraft.class_3218$$Lambda$2853/1028381144.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:676)
	at net.minecraft.class_3218.method_18765(class_3218.java:383)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:827)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:764)
	at net.minecraft.class_1132.method_3748(class_1132.java:128)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at grondag.tdnf.FallingLogEntity.method_5773(FallingLogEntity.java:189)
	at net.minecraft.class_3218.method_18762(class_3218.java:580)
	at net.minecraft.class_3218$$Lambda$2853/1028381144.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: trees-do-not-float:falling_log (grondag.tdnf.FallingLogEntity)
	Entity ID: 1044
	Entity Name: entity.trees-do-not-float.falling_log
	Entity's Exact location: 830.50, 63.00, -405.50
	Entity's Block location: World: (830,63,-406), Chunk: (at 14,3,10 in 51,-26; contains blocks 816,0,-416 to 831,255,-401), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	Immitating BlockState: Block{minecraft:acacia_log}[axis=x,persistent=false]
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:676)
	at net.minecraft.class_3218.method_18765(class_3218.java:383)

-- Affected level --
Details:
	Level name: Superworld
	All players: 1 total; [class_3222['TomRowe'/70, l='Superworld', x=836.24, y=64.00, z=-408.29]]
	Chunk stats: ServerChunkCache: 4050
	Level seed: -561477723984152019
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-192,77,-256), Chunk: (at 0,4,0 in -12,-16; contains blocks -192,0,-256 to -177,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 206895 game time, 243138 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 114353 (now: false), thunder time: 140606 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:827)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:764)
	at net.minecraft.class_1132.method_3748(class_1132.java:128)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 741697128 bytes (707 MB) / 2113929216 bytes (2016 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		blue_endless_jankson: jankson 1.1.2
		cloth-config2: Cloth Config v2 0.2.0
		fabric: Fabric API 0.3.0+build.185
		fabric-api-base: fabric-api-base 0.1.0+59147463
		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c52
		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c52
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+05f11b75
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+59147463
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+59147463
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+59147463
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+59147463
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+59147463
		fabric-models-v0: fabric-models-v0 0.1.0+59147463
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c52
		fabric-networking-v0: fabric-networking-v0 0.1.2+200eb5c2
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9fe2f882
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+baba33ba
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.0+02a46d5b
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.7+029ec62e
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c2
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+59147463
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+c189dc5c
		fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c35
		fabricloader: Fabric Loader 0.4.8+build.155
		trees-do-not-float: Trees Do Not Float 1.3.0+build.26
	Player Count: 1 / 8; [class_3222['TomRowe'/70, l='Superworld', x=836.24, y=64.00, z=-408.29]]
	Data Packs: fabric/fabric-mining-levels-v0, vanilla
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by grondag** [comment]
That version of TDNF is only compatible with Minecraft 1.14.3 because Mojang made changes to how game rules are accessed.   You could use one of the earlier versions of TDNF but I recommend you update to 1.14.3.
