### ISSUE TITLE
Cloth Config API should be a jar-in-jar, not a player download

### ISSUE THREAD

**Issue by matthew-cline** [grondag/trees-dont-float#7]
[From the Cloth Config API page](https://www.curseforge.com/minecraft/mc-mods/cloth-config):

> NOTE: Should be used as jar in a jar.
> 
> You shouldn't be downloading this as a player, this mod is intended for developers. If your game crash without installing this mod, please tell the mod developer to bundle Cloth Config API within their mod!

**Comment by grondag** [comment]
Thank you for trying TDNF.  Version 1.3.0 build 27 does already include Cloth Config API.  If you are getting an error with that version please provide a full log file.

<img width="383" alt="image" src="https://user-images.githubusercontent.com/6106235/61587396-a8cf7100-ab3e-11e9-8661-4962b8bdc1e4.png">
