### ISSUE TITLE
One Missing Log 

### ISSUE THREAD

**Issue by zeyd6796** [grondag/trees-dont-float#9]
When a tree is cut, the tree is dropping one less log (let's suppose there must be 14 logs, it drops 13 logs) on 1.5.0+build.49, unlike the old version 1.4.0+build.30 with default configurations on 1.14.4 SP.

**Comment by grondag** [comment]
Interesting. What is your config? The drop logic varies somewhat based on configuration.

**Comment by zeyd6796** [comment]
Thanks for the tip. Deleting "trees-do-not-float.json5" config file for a fresh install of "1.5.0+build.49" solved the issue with <"keepLogsIntact": false> (which is from the default config) but now I still get one missing log with <"keepLogsIntact": true> unfortunately.

**Comment by zeyd6796** [comment]
Thanks for the hint. Deleting "trees-do-not-float.json5" config file for a fresh install of "1.5.0+build.49" solved the issue with <"keepLogsIntact": false> (which is from the default config) but now I still get one missing log with <"keepLogsIntact": true> unfortunately.
